server:
  port: 8761

eureka:
  instance:
    #hostname: saeurecatest.mybluemix.net:localhost
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.49
    response-cache-update-interval-ms: 1000
    response-cache-auto-expiration-in-seconds: 180
    eviction-interval-timer-in-ms: 1000


spring:
  application:
    name: yp_server